defmodule ExPhil.Training.Config.FlagDocs do
  @moduledoc """
  INVARIANTS.md item 2, phase C: the flag REFERENCE TABLE in
  docs/guides/TRAINING.md is GENERATED from the parser's flag table + the
  config defaults + this description map — never hand-edited. The test
  `flag_docs_test` fails when the committed section drifts from
  `render/0`; regenerate with:

      mix run -e 'ExPhil.Training.Config.FlagDocs.write!()'

  Descriptions were seeded on 2026-09-09 from the hand-written TRAINING.md
  rows; add a new flag's description HERE (the table row in the parser is
  the other half). `undocumented/0` lists table flags with no entry — a
  ratchet in the test.
  """

  alias ExPhil.Training.Config
  alias ExPhil.Training.Config.Parser

  @start_marker "<!-- flag-reference:start (generated by ExPhil.Training.Config.FlagDocs — do not edit) -->"
  @end_marker "<!-- flag-reference:end -->"
  @doc_path "docs/guides/TRAINING.md"

  @docs %{
    "--accumulation-steps" => "Gradient accumulation steps",
    "--action-delay" => "Reaction delay (frames) for the standard path, ON TOP of the causal pairing Peppi emits (state[t] -> the input issued from it). 0 = causal (the default); k pairs state[t] with the input issued k frames later. One concept with --frame-delay. Composes with --prev-action.",
    "--action-horizon" => "Action prediction horizon (for chunked policies)",
    "--action-mode" => "Action embedding: one_hot (399 dims) or learned (64-dim trainable)",
    "--attention-every" => "Add attention every N layers (hybrid)",
    "--attention-interval" => "zamba",
    "--augment" => "Enable data augmentation",
    "--auto-batch-backoff" => "Safety factor (0.8 = 20% headroom)",
    "--auto-batch-max" => "Maximum batch size to test",
    "--auto-batch-min" => "Minimum batch size to test",
    "--auto-batch-size" => "Auto-tune batch size for optimal GPU utilization",
    "--backbone" => "See backbone list below",
    "--backup" => "Create .bak before overwrite",
    "--backup-count" => "Number of backup versions to keep",
    "--balance-characters" => "Weight sampling by inverse char frequency",
    "--batch-size" => "Batch size",
    "--bptt" => "Contiguous-BPTT training: cursors walk replays in order, GRU carry flows across chunks, per-timestep loss (GRU only; see BPTT_LOADER_DESIGN.md)",
    "--bptt-overlap" => "Frames shared between consecutive BPTT chunks (set to frame_delay + 1)",
    "--bptt-val-files" => "Whole replays held out for the carry-threaded val pass (game-level split; val batch is capped at 8 rows)",
    "--button-weight" => "Multiply button loss (fixes under-prediction)",
    "--cache-augmented" => "Precompute augmented variants (~100x speedup)",
    "--cache-dir" => "Cache directory",
    "--cache-embeddings" => "Enable disk caching of embeddings",
    "--cache-streaming" => "Cache chunk embeddings to disk (reuse across epochs)",
    "--character-mode" => "Character embedding: one_hot (33 dims) or learned (64-dim trainable)",
    "--characters" => "Filter replays by character",
    "--checkpoint-every" => "Checkpoint every N layers",
    "--chunk-size" => "Chunk size for chunked/memory-efficient attention",
    "--chunked-attention" => "Use chunked attention for 20-30% memory reduction",
    "--clip-epsilon" => "PPO clipping parameter",
    "--config" => "YAML config file path",
    "--conv-size" => "Convolution kernel size",
    "--corpus" => "Pre-built MmapCorpus dir (`scripts/build_corpus.exs`) — skips parse/embed, trains straight off disk; overrides `--replays`. Temporal only. RAM is O(batch), so corpus size is unbounded (built for the 4,461-game fox_il_v2 run)",
    "--decay-steps" => "Steps for LR decay",
    "--dropout" => "Dropout rate",
    "--dry-run" => "Validate config without training",
    "--dual-port" => "Maximum data, mixed characters",
    "--early-stopping" => "Enable early stopping",
    "--ema" => "Enable model EMA",
    "--ema-decay" => "EMA decay rate",
    "--epochs" => "Number of training epochs",
    "--error-log" => "Log errors to file",
    "--expand-factor" => "Expansion factor",
    "--expand-ratio" => "hgrn, gla",
    "--fail-fast" => "Stop on first error",
    "--flash-attention-nif" => "Use FlashAttention NIF for inference (forward-only, Ampere+ GPU)",
    "--focal-gamma" => "Focal loss gamma (higher = focus on hard)",
    "--focal-loss" => "Enable focal loss for rare actions",
    "--frame-delay" => "Reaction delay (frames) for the streaming/bptt path, ON TOP of the causal pairing Peppi emits (INVARIANTS.md item 1, GOTCHA #113). 0 = causal (the default). Live --frame-delay N plays reaction delay N-1, so a policy trained here at k deploys at N = k+1 (ExPhil.Data.LabelConvention).",
    "--frame-delay-augment" => "Enable frame delay augmentation",
    "--frame-delay-max" => "Maximum reaction delay when augmenting",
    "--frame-delay-min" => "Minimum reaction delay when augmenting (0 = causal)",
    "--gae-lambda" => "GAE lambda for advantage estimation",
    "--game-type" => "Game type: mock, dolphin, libmelee",
    "--gc-every" => "Run garbage collection every N batches (0=disabled)",
    "--gradient-checkpoint" => "Trade memory for compute",
    "--head" => "Controller head: `independent` (six parallel heads) or `autoregressive` (residual-stream conditional head, buttons→main_x→main_y→c_x→c_y→shoulder; see AUTOREGRESSIVE_HEAD_PLAN.md). Temporal only",
    "--head-dim" => "Attention head width",
    "--hidden" => "Hidden layer sizes",
    "--hide-errors" => "Hide individual file errors",
    "--integration-steps" => "ODE sub-steps per frame",
    "--jumps-normalized" => "Jumps as 1 normalized dim (false = 7-dim one-hot)",
    "--keep-best" => "Keep best N checkpoints (prune others)",
    "--kl-weight" => "KL divergence weight for ACT (CVAE)",
    "--kmeans-centers" => "K-means cluster centers for sticks",
    "--label-smoothing" => "Label smoothing (prevents overconfidence)",
    "--layer-norm" => "Enable layer normalization (MLP)",
    "--learn-player-styles" => "Enable style-conditional training",
    "--log-file" => "Tee script output to a file",
    "--log-interval" => "Progress bar update frequency (every N batches)",
    "--lr" => "Learning rate (alias: `--learning-rate`)",
    "--lr-schedule" => "cosine, linear, exponential",
    "--max-episode-frames" => "Max frames per episode (~8 min at 60fps)",
    "--max-files" => "Limit number of replay files",
    "--max-grad-norm" => "Gradient clipping norm (0 = disabled)",
    "--memory-efficient-attention" => "Use memory-efficient attention (true O(n) memory via online softmax)",
    "--min-delta" => "Minimum improvement to count as progress",
    "--min-player-games" => "Min games for player to be in registry",
    "--min-quality" => "Minimum quality score (0-100) for replays",
    "--mirror-prob" => "Mirror augmentation probability",
    "--mix-corpus" => "Corpus-mode curriculum mixing: a snippet mini-corpus (`scripts/build_snippet_corpus.exs`, one corpus file per snippet so windows never cross snippet boundaries) whose batches are interleaved evenly into the `--corpus` training stream. Embed sizes must match. Mix files are all-train (val stays comparable to unmixed baselines).",
    "--mix-frames" => "Curriculum mixing: comma/glob list of drill `.frames` exports (`scripts/export_drill_frames.exs`) concatenated into training. Drill frames must be exported at the SAME `--action-delay` (the prev-action channel misaligns otherwise; a warning fires). Changes the embedding cache key. Replay mode only — corpus mode ignores it (use `--mix-corpus`).",
    "--mix-oversample" => "Passes of the mix corpus interleaved per epoch. The mix is typically a tiny fraction of the main corpus — oversample to give corrections a meaningful gradient share (e.g. 20 ≈ a few percent for a 41M-frame corpus with ~15k mix frames).",
    "--mixed-precision" => "FP32 master weights + BF16 compute (not recommended)",
    "--mmap-embeddings" => "Use memory-mapped embeddings (for datasets > RAM)",
    "--mmap-path" => "Custom path for mmap file (auto-generated if not set)",
    "--multi-delay" => "Train one policy across delay rungs; per-frame delay-id tags (drill only). {2,3} is the production recipe",
    "--name" => "Custom checkpoint name",
    "--nana-mode" => "Ice Climbers Nana: compact (39), enhanced (14+ID), full (449)",
    "--neutral-weight" => "Per-frame loss weight for neutral (no-input) frames; action frames get 1.0. Blanket anti-passivity knob — 1.0 = unweighted (the 09-05 clean-loss arm), which raised idle 6.5x corpus at v2 scale.",
    "--no-backup" => "Skip backup creation",
    "--no-cache" => "Ignore existing cache and recompute",
    "--no-cache-streaming" => "Disable streaming cache",
    "--no-chunked-attention" => "Disable chunked attention",
    "--no-flash-attention-nif" => "Disable FlashAttention NIF",
    "--no-layer-norm" => "Disable layer normalization",
    "--no-memory-efficient-attention" => "Disable memory-efficient attention",
    "--no-overwrite" => "Fail if checkpoint exists",
    "--no-pipeline-chunks" => "Disable chunk pipelining (sequential processing)",
    "--no-precompute" => "Disable embedding precomputation",
    "--no-prefetch" => "Disable batch prefetching",
    "--no-qk-layernorm" => "Disable QK LayerNorm",
    "--no-register" => "Skip model registry",
    "--no-residual" => "Disable residual connections",
    "--no-skip-duplicates" => "Include all files even if duplicates",
    "--noise-prob" => "Noise augmentation probability",
    "--noise-scale" => "Noise magnitude",
    "--num-games" => "Number of parallel games to run",
    "--num-heads" => "Number of attention heads (parsed since 2026-09-09 — it was accepted-and-ignored before, and Trainer's private 2/32 table won)",
    "--num-inference-steps" => "Diffusion/flow matching inference steps",
    "--num-layers" => "Number of Mamba layers",
    "--num-noisy-variants" => "Number of noisy variants to precompute",
    "--num-player-names" => "Player name dims (0 to disable)",
    "--offstage-weight" => "(bptt path) Per-frame loss weight for OFFSTAGE frames (subject airborne beyond the stage ledge): `max(weight, X)`. Rare-state coverage for recovery — offstage is rare in expert play, so the model gets few reps where it fails. Added 2026-09-08.",
    "--online-robust" => "Enable online play training mode (legacy path)",
    "--optimizer" => "adam, adamw, lamb, radam",
    "--overwrite" => "Allow overwriting existing checkpoints",
    "--patience" => "Epochs without improvement before stopping",
    "--per-stage-ledge" => "Task #25: use the real per-stage edge x (`Melee.Stages.edge_ground_position`) in the ledge-distance feature instead of the historical 85-everywhere constant (which reads \"safe\" at x=60 on YS when the player is offstage). Changes the embedding VALUES: existing checkpoints and corpora are calibrated to the constant, so this is for fresh v3-edge arms only, and corpus-mode training needs a corpus REBUILT with the same flag (recorded in corpus meta).",
    "--pipeline-chunks" => "Prepare next chunk while training (overlaps CPU/GPU)",
    "--pipeline-offset" => "Label shift = delay + N; the measured live pipeline is +2 (drill only)",
    "--player-port" => "Know which port to train on",
    "--player-registry" => "Save/load player registry JSON",
    "--policy-type" => "Policy architecture type",
    "--ppo-epochs" => "PPO update epochs per batch",
    "--precision" => "f32 or bf16 (FP32 is 2x faster due to XLA issues)",
    "--precompute" => "Precompute embeddings (2-3x speedup)",
    "--prefetch" => "Prefetch batches while GPU trains",
    "--prefetch-buffer" => "Number of batches to prefetch",
    "--preset" => "Training preset (quick, standard, full, mewtwo)",
    "--prev-action" => "Condition on previous frame's controller (training embeds frame i-1's inputs; live agent feeds back its own outputs). Enables frame-precise input sequences (dash dance, multishine). Regime is stored in the policy config — old checkpoints keep zeros. Not yet wired for --streaming.",
    "--prev-action-dropout" => "Zero the prev-action channel on fraction P of training frames (exposure-bias mitigation: live, the model feeds back its own outputs, which drift from teacher-forced ground truth). Try 0.1–0.3 with --prev-action. Mask is baked into the embedding cache entry — use --no-cache for a fresh mask.",
    "--probe-basin" => "Per-epoch basin mental rollout + (multishine script) fixture margins to `<out>.basin_probe.jsonl`; `--no-probe-basin` disables",
    "--probe-entries" => "Dead-seed replays as auto-detected absorbed probe entries",
    "--profile" => "Enable timing profiler (report at end)",
    "--qk-layernorm" => "Normalize Q/K before attention (stabilizes training)",
    "--queue-depth" => "Queue-as-input: last K decoded actions as input channels (drill only)",
    "--quiet" => "Minimal output (errors only), suppresses XLA/ptxas logs",
    "--reinit-head" => "With `--resume`: re-initialise the controller head from scratch while loading the trunk (the \"new head params\" control, AUTOREGRESSIVE_HEAD_PLAN item 9)",
    "--replays" => "Directory containing .slp files",
    "--residual" => "Enable residual connections (MLP)",
    "--restart-mult" => "Restart period multiplier (T_mult)",
    "--restart-period" => "Cosine annealing restart period (T_0)",
    "--resume" => "Resume from checkpoint. If the checkpoint's controller head differs from `--head`, the TRUNK is transplanted: matching non-head params load, head + optimizer start fresh, config/step keep the trainer's",
    "--save-best" => "Save model when val_loss improves",
    "--save-every" => "Save checkpoint every N epochs",
    "--save-every-batches" => "Save checkpoint every N batches (for streaming)",
    "--scheduled-sampling" => "Exposure bias: on fraction P of samples, replace the LAST window position's prev-action slice with the model's OWN decoded prediction (`ExPhil.Training.ScheduledSampling`; decode pinned to the live path). Requires `--temporal` and `--prev-action`. One extra forward pass per step. Loss under this flag is a harder objective — never compare loss curves across it; judge by live runs.",
    "--seed" => "Random seed for reproducibility",
    "--select-character-port" => "With `--train-character`: imitate that character's actual port per file (singles → their port, dittos → port 1). Without it the streaming loader imitates port 1 regardless (the fox_gen_v1 43%-non-fox corpus bug, E1). Streaming pipeline only",
    "--show-errors" => "Show individual file errors",
    "--show-quality-stats" => "Show quality distribution after filtering",
    "--skip-duplicates" => "Skip duplicate replay files by hash",
    "--skip-errors" => "Continue past bad replay files",
    "--snippet-frames" => "Mix pre-relabeled snippet files from `snippet_mine.exs` (drill only)",
    "--solver" => "ODE solver: euler, midpoint, rk4, dopri5",
    "--ss-ramp" => "Ramp scheduled sampling 0 → P linearly over the first N epochs (drill loop; the main pipeline currently applies P flat).",
    "--stage-internals" => "Add FoD platform heights + PS transformation to the embedding (+7 raw dims, zero-gated by stage; W4 2026-08-24 stage-blindness verdict)",
    "--stage-mode" => "Stage embedding: full, compact, learned",
    "--stages" => "Filter replays by stage",
    "--state-size" => "SSM state dimension",
    "--stick-edge-weight" => "Weight edge stick buckets higher (try 2.0-3.0)",
    "--stream-chunk-size" => "Load N files at a time (memory-bounded)",
    "--stride" => "Step between sequences",
    "--temporal" => "Enable temporal training",
    "--track-elo" => "Enable Elo rating tracking",
    "--train-character" => "1x (filtered)",
    "--transition-weight" => "Per-frame loss weight for DECISION frames (controller differs from the previous frame): `max(weight, X)`. Targets *when* to change action (leaving WAIT, committing) instead of downweighting all neutral frames. Flag added 2026-09-07 (was pipeline/drill-only).",
    "--truncate-bptt" => "Truncated backprop (faster training)",
    "--unroll" => "BPTT chunk length in frames (gradient truncation horizon)",
    "--val-concurrency" => "Parallel validation batches (1=sequential)",
    "--val-split" => "Validation split (0.1 = 10%)",
    "--verbose" => "Debug output (timing, memory)",
    "--wandb" => "Enable Weights & Biases logging",
    "--wandb-name" => "W&B run name (auto-generated if nil)",
    "--wandb-project" => "W&B project name",
    "--warmup-steps" => "Learning rate warmup steps",
    "--window-size" => "Frames per sequence",
    "--with-delay-id" => "Delay-id one-hot input (size 9, ids 0-8; never deploy at an untrained id — override instead)",  }

  @doc "Description for a flag, or nil."
  @spec describe(String.t()) :: String.t() | nil
  def describe(flag), do: Map.get(@docs, flag)

  @doc "Table flags with no description (ratchet)."
  @spec undocumented() :: [String.t()]
  def undocumented do
    Parser.flags() |> Enum.reject(&Map.has_key?(@docs, &1)) |> Enum.sort()
  end

  @doc "Render the generated reference table (markdown)."
  @spec render() :: String.t()
  def render do
    defaults = Config.defaults()

    rows =
      Parser.flag_table()
      |> Enum.map(fn {flag, key, type} ->
        default = Keyword.get(defaults, key)
        "| `#{flag}` | #{type_name(type)} | `#{inspect(default)}` | #{describe(flag) || "_(undocumented)_"} |"
      end)

    special =
      (Parser.flags() -- Enum.map(Parser.flag_table(), &elem(&1, 0)))
      |> Enum.sort()
      |> Enum.map(fn flag -> "| `#{flag}` | special | — | #{describe(flag) || "_(undocumented)_"} |" end)

    Enum.join(
      [
        @start_marker,
        "",
        "## Flag reference (generated)",
        "",
        "Every training flag `scripts/train.exs` accepts, straight from the parser table",
        "(`ExPhil.Training.Config.Parser.flag_table/0`) and `Config.defaults/0`.",
        "Regenerate: `mix run -e 'ExPhil.Training.Config.FlagDocs.write!()'`.",
        "",
        "| flag | type | default | description |",
        "|---|---|---|---|"
      ] ++ rows ++ special ++ ["", @end_marker],
      "\n"
    )
  end

  @doc "Splice the rendered table into TRAINING.md between the markers (append if absent)."
  @spec write!() :: :ok
  def write! do
    md = File.read!(@doc_path)
    section = render()

    new =
      if String.contains?(md, @start_marker) do
        Regex.replace(~r/#{Regex.escape(@start_marker)}.*?#{Regex.escape(@end_marker)}/s, md, section)
      else
        md <> "\n\n" <> section <> "\n"
      end

    File.write!(@doc_path, new)
  end

  @doc "The section currently committed in TRAINING.md (nil if absent)."
  @spec committed() :: String.t() | nil
  def committed do
    md = File.read!(@doc_path)

    case Regex.run(~r/#{Regex.escape(@start_marker)}.*?#{Regex.escape(@end_marker)}/s, md) do
      [s] -> s
      _ -> nil
    end
  end

  defp type_name({:atom, _}), do: "atom"
  defp type_name({:atom_list, _}), do: "atom list"
  defp type_name(t) when is_atom(t), do: t |> Atom.to_string() |> String.replace("_", " ")
end
