#!/usr/bin/env python3
"""
AOT compile the Triton linear scan kernel to cubin.

Outputs:
  - linear_scan_kernel.cubin  (GPU binary for sm_75)
  - linear_scan_metadata.py   (launch config: num_warps, shared_mem, etc.)

Usage:
  python3 compile_aot.py
  python3 compile_aot.py --sm 75   # Target compute capability (default: 75 for T400)
"""

import argparse
import os
import struct
import sys

import triton
import triton.language as tl
from triton.compiler import ASTSource, compile as triton_compile
from triton.backends.nvidia.compiler import GPUTarget

from linear_scan_kernel import linear_scan_kernel


def compile_kernel(sm: int = 75):
    """AOT compile linear_scan_kernel to cubin targeting sm_{sm}."""

    print(f"Compiling linear_scan_kernel for sm_{sm}...")

    # Define signature: all pointers are *fp32, scalars are i32
    # Triton AOT compilation needs explicit type signature
    signature = {
        0: "*fp32",  # a_ptr
        1: "*fp32",  # b_ptr
        2: "*fp32",  # h0_ptr
        3: "*fp32",  # output_ptr
        4: "i32",    # batch
        5: "i32",    # seq_len
        6: "i32",    # hidden
    }

    # Compile via ASTSource (Triton 3.x API)
    # Use direct GPUTarget to avoid torch dependency for driver auto-detection
    src = ASTSource(
        fn=linear_scan_kernel,
        signature=signature,
        constants={},
    )

    target = GPUTarget("cuda", sm, 32)

    compiled = triton_compile(
        src=src,
        target=target,
    )

    # Extract cubin and metadata
    cubin = compiled.asm["cubin"]
    metadata = compiled.metadata

    # Write cubin
    cubin_path = "linear_scan_kernel.cubin"
    with open(cubin_path, "wb") as f:
        f.write(cubin)
    print(f"  Written: {cubin_path} ({len(cubin)} bytes)")

    # Write metadata as C header for the NIF
    header_path = "linear_scan_kernel_meta.h"
    num_warps = metadata.num_warps
    shared_mem = metadata.shared
    kernel_name = compiled.metadata.name

    with open(header_path, "w") as f:
        f.write(f"// Auto-generated by compile_aot.py\n")
        f.write(f"// Target: sm_{sm}\n")
        f.write(f"#define TRITON_KERNEL_NAME \"{kernel_name}\"\n")
        f.write(f"#define TRITON_NUM_WARPS {num_warps}\n")
        f.write(f"#define TRITON_SHARED_MEM {shared_mem}\n")
        f.write(f"#define TRITON_CUBIN_SIZE {len(cubin)}\n")
    print(f"  Written: {header_path}")

    # Write metadata as text for debugging
    print(f"\n  Kernel name: {kernel_name}")
    print(f"  Num warps: {num_warps}")
    print(f"  Shared memory: {shared_mem} bytes")
    print(f"  Cubin size: {len(cubin)} bytes")

    return cubin_path, header_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AOT compile Triton linear scan kernel")
    parser.add_argument("--sm", type=int, default=75, help="Target SM version (default: 75 for T400)")
    args = parser.parse_args()

    compile_kernel(sm=args.sm)
    print("\nDone! Build the NIF with: make && make install")
